version: '3.9'

services:
  backend:
    build: .BACKEND
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "8081:8081"
  
volumes:
  mongo_data:

